blank_issues_enabled: true
contact_links:
  - name: ğŸ’¬ è³ªå•ãƒ»ç›¸è«‡
    url: https://github.com/Narumikr/link-sekai-actions/discussions
    about: ä½¿ã„æ–¹ã®è³ªå•ã‚„ç›¸è«‡ã¯Discussionsã§ãŠæ°—è»½ã«ã©ã†ãï¼
