# .github/workflows/prsk-pr-labeling.yml
name: PR prsk labeling

on:
  pull_request:
    types: [opened]

permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  add-character-label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add prsk label
        uses: ./prsk-pr-labeling
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}